[build-system]
requires = [
    "setuptools>=68",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name="rbtn"
version="0.1.10"
description="convert non-standard words to spoken-form words"
readme = "src/rbtn/README.md"
requires-python=">=3.8"


[tool.setuptools]
package-dir={""="src"}


[tool.setuptools.packages.find]
where=["src"]


[tool.cibuildwheel]

build=[
"cp39-*",
"cp310-*",
"cp311-*",
"cp312-*",
"cp313-*"
]

skip=[
"*-musllinux*",
"*win32",
"*t-*"
]

build-verbosity = 3