[build-system]
requires = [
    "setuptools>=68",
    "wheel",
    "setuptools-scm"
]
build-backend = "setuptools.build_meta:__legacy__"


[project]
name = "rbtn"
version = "0.1.8"
description = "convert non-standard words to spoken-form words"
requires-python = ">=3.8"


[tool.setuptools]
package-dir = {"" = "src"}


[tool.setuptools.packages.find]
where = ["src"]


[tool.setuptools.package-data]
rbtn = [
    "*.so",
    "*.dll",
    "*.dylib",
    "*.txt"
]

[tool.cibuildwheel]
build = [
    "cp39-*",
    "cp310-*",
    "cp311-*",
    "cp312-*",
    "cp313-*"
]

skip = [
    "*-musllinux*",
    "*t-*"
]

