name: Build wheels

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
          - macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.0
        env:
          CIBW_BEFORE_BUILD_LINUX: >
            gcc -shared -fPIC -O3
            C/RBTN.c C/TNlib.c
            -o src/rbtn/pypiRBTN.so &&
            file src/rbtn/pypiRBTN.so

          CIBW_BEFORE_BUILD_WINDOWS: >
            call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars64.bat" &&
            where cl &&
            cl /LD /O2 C\RBTN.c C\TNlib.c /Fe:src\rbtn\pypiRBTN.dll &&
            dir src\rbtn\pypiRBTN.dll

          CIBW_BEFORE_BUILD_MACOS: >
            clang -shared -O3
            C/RBTN.c C/TNlib.c
            -o src/rbtn/pypiRBTN.dylib &&
            file src/rbtn/pypiRBTN.dylib &&
            lipo -info src/rbtn/pypiRBTN.dylib &&
            ls -lh src/rbtn/

        with:
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl